openapi: 3.2.0
info:
  version: v2.222.1
  title: Corva Dataset Types API
  description: 'The Corva API is a powerful interface providing great flexibility and extensibility with Corva. Whether your needs are simple UI visualizations, data entry, replication/sync tasks, real-time stream processing, or complex machine learning CPU-intensive apps, the Corva API is the way to make it happen. Our concepts are split into three distinct silos: data apps, visualization apps, and a REST API'
  termsOfService: https://www.corva.ai/terms-and-conditions/
  contact:
    name: Corva API Team
    email: support@corva.ai
security:
- api_key: []
tags:
- name: DatasetTypes
paths:
  /v2/dataset_types:
    get:
      summary: List DatasetTypes
      tags:
      - DatasetTypes
      responses:
        '401':
          description: Authentication error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthenticationError'
        '403':
          description: Authorization error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthorizationError'
        '404':
          description: Not found error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundError'
        '200':
          type: object
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DatasetTypeList'
      operationId: getV2DatasetTypes
      x-operation-id-source: derived
  /v2/datset_types/{id}:
    get:
      summary: Show DatasetType
      tags:
      - DatasetTypes
      responses:
        '401':
          description: Authentication error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthenticationError'
        '403':
          description: Authorization error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthorizationError'
        '404':
          description: Not found error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundError'
        '200':
          type: object
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DatasetType'
      parameters:
      - in: path
        name: id
        description: DatasetType ID
        required: true
        schema:
          type: integer
          format: int64
      operationId: getV2DatsetTypesById
      x-operation-id-source: derived
    patch:
      summary: Update an DatasetType
      tags:
      - DatasetTypes
      responses:
        '401':
          description: Authentication error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthenticationError'
        '403':
          description: Authorization error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthorizationError'
        '404':
          description: Not found error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundError'
        '200':
          description: Updated DatasetType
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DatasetType'
      parameters:
      - in: path
        name: id
        description: DatasetType ID
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DatasetTypePayload'
        description: DatasetType Payload
        required: true
      operationId: patchV2DatsetTypesById
      x-operation-id-source: derived
components:
  schemas:
    AuthorizationError:
      required:
      - code
      - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
      example:
        code: 403
        message: Access denied
    NotFoundError:
      required:
      - code
      - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
      example:
        code: 404
        message: Not found
    AuthenticationError:
      required:
      - code
      - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
      example:
        code: 401
        message: Missing authentication. Please try again.
    DatasetType:
      properties:
        identifier:
          type: string
        name:
          type: string
        doc_description:
          type: string
      example:
        id: 12345
        type: dataset_type
        attributes:
          id: 12345
          identifier: time
          name: Time
          doc_description: '[{''type'':''paragraph'',''children'':[{''text'':''These are the Backend apps...''}]}]'
    DatasetTypeList:
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/DatasetType'
    DatasetTypePayload:
      properties:
        doc_intro:
          type: string
        doc_description:
          type: string
        doc_content:
          type: string
  securitySchemes:
    api_key:
      type: apiKey
      name: authorization
      in: header
