openapi: 3.2.0
info:
  version: v2.222.1
  title: Corva Ability Check API
  description: 'The Corva API is a powerful interface providing great flexibility and extensibility with Corva. Whether your needs are simple UI visualizations, data entry, replication/sync tasks, real-time stream processing, or complex machine learning CPU-intensive apps, the Corva API is the way to make it happen. Our concepts are split into three distinct silos: data apps, visualization apps, and a REST API'
  termsOfService: https://www.corva.ai/terms-and-conditions/
  contact:
    name: Corva API Team
    email: support@corva.ai
security:
- api_key: []
tags:
- name: AbilityCheck
  description: Check abilities for user
paths:
  v2/ability_check/check_feature:
    get:
      summary: Check feature status for user
      tags:
      - AbilityCheck
      responses:
        '401':
          description: Authentication error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthenticationError'
        '403':
          description: Authorization error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthorizationError'
        '404':
          description: Not found error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundError'
        '200':
          type: object
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FeatureStatus'
      parameters:
      - in: query
        name: feature_name
        description: Name of Feature
        required: true
        schema:
          type: string
      operationId: getV2AbilityCheckCheckFeature
      x-operation-id-source: derived
  v2/ability_check/check_permission:
    get:
      summary: Check permission status for user
      tags:
      - AbilityCheck
      responses:
        '401':
          description: Authentication error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthenticationError'
        '403':
          description: Authorization error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthorizationError'
        '404':
          description: Not found error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundError'
        '200':
          type: object
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PermissionStatus'
      parameters:
      - in: query
        name: ability
        description: Ability to check
        required: true
        schema:
          type: string
      - in: query
        name: resource_class
        description: Class of resource
        required: true
        schema:
          type: string
      - in: query
        name: resource_id
        description: Id of resource if checking permission for particular entity
        required: false
        schema:
          type: integer
      - in: query
        name: name
        description: Dataset name
        required: false
        schema:
          type: integer
      - in: query
        name: provider
        description: Dataset provider
        required: false
        schema:
          type: integer
      operationId: getV2AbilityCheckCheckPermission
      x-operation-id-source: derived
components:
  schemas:
    AuthorizationError:
      required:
      - code
      - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
      example:
        code: 403
        message: Access denied
    NotFoundError:
      required:
      - code
      - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
      example:
        code: 404
        message: Not found
    AuthenticationError:
      required:
      - code
      - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
      example:
        code: 401
        message: Missing authentication. Please try again.
    PermissionStatus:
      properties:
        active:
          type: boolean
      example:
        active: 'true'
    FeatureStatus:
      properties:
        active:
          type: boolean
        total:
          type: integer
        used:
          type: integer
      example:
        active: 'true'
        total: 10
        used: 2
  securitySchemes:
    api_key:
      type: apiKey
      name: authorization
      in: header
