openapi: 3.2.0
info:
  version: v2.222.1
  title: Corva Message Producer API
  description: 'The Corva API is a powerful interface providing great flexibility and extensibility with Corva. Whether your needs are simple UI visualizations, data entry, replication/sync tasks, real-time stream processing, or complex machine learning CPU-intensive apps, the Corva API is the way to make it happen. Our concepts are split into three distinct silos: data apps, visualization apps, and a REST API'
  termsOfService: https://www.corva.ai/terms-and-conditions/
  contact:
    name: Corva API Team
    email: support@corva.ai
security:
- api_key: []
tags:
- name: MessageProducer
  description: Message Producer for apps
paths:
  /message_producer:
    post:
      summary: Produce messages for sent data
      tags:
      - MessageProducer
      responses:
        '401':
          description: Authentication error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthenticationError'
        '403':
          description: Authorization error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthorizationError'
        '404':
          description: Not found error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundError'
        '200':
          description: Successful response
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MessageProducerPayload'
        description: Data for message production
        required: true
      operationId: postMessageProducer
      x-operation-id-source: derived
components:
  schemas:
    MessageProducerPayload:
      properties:
        app_connection_id:
          type: integer
        asset_id:
          type: integer
        rerun_begins:
          type: integer
        data:
          type: array
      example:
        app_connection_id: 123445
        asset_id: 123445
        rerun_begins: 1
        data: []
    AuthorizationError:
      required:
      - code
      - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
      example:
        code: 403
        message: Access denied
    NotFoundError:
      required:
      - code
      - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
      example:
        code: 404
        message: Not found
    AuthenticationError:
      required:
      - code
      - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
      example:
        code: 401
        message: Missing authentication. Please try again.
  securitySchemes:
    api_key:
      type: apiKey
      name: authorization
      in: header
