openapi: 3.2.0
info:
  version: v2.222.1
  title: Corva Search Suggestions API
  description: 'The Corva API is a powerful interface providing great flexibility and extensibility with Corva. Whether your needs are simple UI visualizations, data entry, replication/sync tasks, real-time stream processing, or complex machine learning CPU-intensive apps, the Corva API is the way to make it happen. Our concepts are split into three distinct silos: data apps, visualization apps, and a REST API'
  termsOfService: https://www.corva.ai/terms-and-conditions/
  contact:
    name: Corva API Team
    email: support@corva.ai
security:
- api_key: []
tags:
- name: Search Suggestions
paths:
  /v2/search_suggestions:
    get:
      summary: Search suggestions for App, Workflow and Article
      tags:
      - Search Suggestions
      responses:
        '401':
          description: Authentication error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthenticationError'
        '403':
          description: Authorization error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthorizationError'
        '404':
          description: Not found error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundError'
        '200':
          type: object
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchSuggestionResult'
      parameters:
      - in: query
        name: search
        description: Search keyword to filter results
        schema:
          type: string
      operationId: getV2SearchSuggestions
      x-operation-id-source: derived
components:
  schemas:
    AuthorizationError:
      required:
      - code
      - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
      example:
        code: 403
        message: Access denied
    NotFoundError:
      required:
      - code
      - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
      example:
        code: 404
        message: Not found
    AuthenticationError:
      required:
      - code
      - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
      example:
        code: 401
        message: Missing authentication. Please try again.
    SearchSuggestionItem:
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        type:
          type: string
      example:
        id: 111
        name: An app name
        type: App
    SearchSuggestionResult:
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/SearchSuggestionItem'
      example:
        data:
        - id: 111
          name: An app name
          type: App
  securitySchemes:
    api_key:
      type: apiKey
      name: authorization
      in: header
